--删除同步LIMS项目主数据同步指令与数据
DELETE FROM V2_EAI_LIMS_PROJECTINFOCOMMAND;
DELETE FROM V2_EAI_PROJECT;
DELETE FROM V2_EAI_PROJECTINFO;

--删除LIMS报工数据
DELETE FROM V2_EQUIPMENT;
DELETE FROM V2_USAGEITEM;
DELETE FROM V2_RPT_USAGEITEM;
DELETE FROM V2_USAGE;
--删除UCS报工数据
DELETE FROM V2_TIMESHEETITEM;
DELETE FROM V2_RPT_TIMESHEETITEM;
DELETE FROM V2_TIMESHEET;
--删除报工同步指令
DELETE FROM V2_EAI_COMMAND;