SELECT P.PROJ_SHORT_NAME  			AS PROJ_CODE,
	        P.INTERNALORDER    			AS PROJ_INTERNALORDER,
	        P.PROJ_NAME     	 				AS PROJ_DESCRIPTION,
	        CO1.CODE_NAME      			AS PROJ_CATEGORY,
	        CO2.CODE_NAME      			AS PROJ_HNTE,
	        CO3.CODE_NAME          		AS PROJ_TECH_CATEGORY,
	        PHT.ENAME         				AS PH1,
	        PH.ENAME           				AS PH2,
	        PH.PARENT_ID       				AS PH1_CODE,
	        PH.PH_ID           					AS PH2_CODE,
	        C.COMPANY_NAME_CN 			AS CUSTOMER_GROUP,
	        C.SAP_CODE         				AS SAP_CODE,
	        C.SAP_NAME         				AS SAP_NAME 
    FROM CM_PROJ P 
	 LEFT JOIN CM_PH PH ON P.PH2 = PH.PH_ID 
	 LEFT JOIN CM_PH PHT ON PH.PARENT_ID = PHT.PH_ID 
	 LEFT JOIN CM_CUSTOMER C ON P.CUSTOMER = C.CUSTOMER_ID 
	 LEFT JOIN CM_CODE CO1 ON P.PROJ_TYPE = CO1.ID 
	 LEFT JOIN CM_CODE CO2 ON P.HNTE = CO2.ID
	 LEFT JOIN CM_CODE CO3 ON P.TECH_CTGRY_1 = CO3.ID 
   WHERE P.ORIG_PROJ_ID IS NULL 
	   AND P.PROJ_NODE_FLAG = 'Y' 