SELECT 
	   O.OVERHEAD_CODE 			AS PROJ_CODE,
       O.INTERNAL_ORDER 			AS PROJ_INTERNALORDER,
       O.OVERHEAD_NAME 			AS PROJ_DESCRIPTION,
       O.PROJECT_CATEGORY 		AS PROJ_CATEGORY,
       O.HNTE 							AS PROJ_HNTE,
       O.PH1 							AS PH1,
       O.PH2 							AS PH2,
       O.PH1_CODE 					AS PH1_CODE,
       O.PH2_CODE 					AS PH2_CODE,
       C.COMPANY_NAME_CN 		AS CUSTOMER_GROUP 
  FROM CM_OVERHEAD O 
  LEFT JOIN CM_CUSTOMER C  ON O.CUSTOMER_GROUP = C.CUSTOMER_ID 